apiVersion: apps/v1
kind: Deployment
metadata:
  name: learningdiaryweb-deployment
  labels:
    app: learningdiaryweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learningdiaryweb
  template:
    metadata:
      labels:
        app: learningdiaryweb
    spec:
      containers:
        - name: learningdiaryweb
          image: learningdiaryacr.azurecr.io/learningdiaryweb:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: LearningDiaryApiUrl
              valueFrom:
                  configMapKeyRef:
                    name: learningdiaryweb-configmap
                    key: learningdiaryapi_url
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: learningdiaryweb-service
spec:
  type: LoadBalancer
  selector:
    app: learningdiaryweb
  ports:
    - protocol: TCP
      port: 80