apiVersion : apps/v1
kind: Deployment
metadata:
  name: learningdiaryapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learningdiaryapi
  template:
    metadata:
      labels:
        app: learningdiaryapi 
    spec:
      containers:
        - name: learningdiaryapi 
          image: learningdiaryacr.azurecr.io/learningdiaryapi
          ports:
          - containerPort: 80