apiVersion: apps/v1
kind: Deployment
metadata:
  name: learningdiaryapi-deployment
  labels:
    app: learningdiaryapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learningdiaryapi
  template:
    metadata:
      labels:
        app: learningdiaryapi
    spec:
      containers:
        - name: learningdiaryapi
          image: learningdiaryacr.azurecr.io/learningdiaryapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom: 
                configMapKeyRef:
                  name: mongo-configmap
                  key: connection_string
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
      imagePullSecrets:
       - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: learningdiaryapi-service
spec:
  selector:
    app: learningdiaryapi
  ports:
    - protocol: TCP
      port: 80