apiVersion: apps/v1
kind: Deployment
metadata:
  name: learningdiaryapi-deployment
  labels:
    app: learningdiaryapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learningdiaryapi
  template:
    metadata:
      labels:
        app: learningdiaryapi
    spec:
      containers:
        - name: learningdiaryapi
          image: jaggedfell/learningdiaryapi:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              valueFrom: 
                configMapKeyRef:
                  name: mongo-configmap
                  key: connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: learningdiaryapi-service
spec:
  type: NodePort
  selector:
    app: learningdiaryapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 31000
